"""
Django settings for qubit project.

Generated by 'django-admin startproject' using Django 1.11b1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
from .qubit_secrets import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'contact.qbit@gmail.com'
EMAIL_HOST_PASSWORD = qubit_EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 31536000
SECRET_KEY = qubit_SECRET_KEY
DEBUG = False
SESSION_COOKIE_SECURE = True
TEMPLATE_DEBUG = DEBUG
ALLOWED_HOSTS = [u'qubit.pythonanywhere.com']
SECURE_SSL_REDIRECT = True
RECAPTCHA_SUBMISSION_SECRET = qubit_RECAPTCHA_SUBMISSION_SECRET
RECAPTCHA_AUTH_SECRET = qubit_RECAPTCHA_AUTH_SECRET

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'problem.apps.ProblemConfig',
    'blog.apps.BlogConfig',
    'contest.apps.ContestConfig',
    'problemset.apps.ProblemsetConfig',
    'mail.apps.MailConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.RobotSecurity',
    'main.middleware.UserState',
]

ROOT_URLCONF = 'qubit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qubit.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': qubit_DATABASE_ENGINE,
        'NAME': qubit_DATABASE_NAME,
        'USER': qubit_DATABASE_USER,
        'PASSWORD': qubit_DATABASE_PASSWORD,
        'HOST': qubit_DATABASE_HOST,
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = True

MEDIA_ROOT = qubit_MEDIA_ROOT
MEDIA_URL = '/media/'
STATIC_ROOT = qubit_STATIC_ROOT
STATIC_URL = '/static/'
